"""Generated, evidence-bounded Phase 7 collection status document."""

from __future__ import annotations

from collections.abc import Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from astock.core.atomic import atomic_write_text
from astock.schemas import ShadowEvaluationReport, ShadowPerformanceStatus
from astock.shadow.service import ShadowEvaluationService


def write_phase7_status(
    service: ShadowEvaluationService,
    path: Path,
    *,
    generated_at: datetime | None = None,
    migration_integrity_issue: str | None = None,
) -> Path:
    """Atomically refresh ``phase7_status.md`` from SQLite/ObjectStore facts."""

    target = path.resolve()
    atomic_write_text(
        target,
        render_phase7_status(
            service,
            generated_at=generated_at,
            migration_integrity_issue=migration_integrity_issue,
        ),
    )
    return target


def render_phase7_status(
    service: ShadowEvaluationService,
    *,
    generated_at: datetime | None = None,
    migration_integrity_issue: str | None = None,
) -> str:
    """Render current counts without promoting missing evidence into results."""

    timestamp = (generated_at or datetime.now(UTC)).astimezone(UTC)
    status = service.status()
    report = _latest_report(service, status.study_id, status.report_id)
    required = status.required_independent_decision_count
    lines = [
        "# Phase 7 Status",
        "",
        "<!-- Generated by `uv run astock phase7-status-update`; do not hand-edit counts. -->",
        "",
        f"- Updated at (UTC): `{timestamp.isoformat()}`",
        f"- Evidence status: `{status.status}`",
        (
            "- Migration integrity: `BLOCKED_CHECKSUM_MISMATCH`"
            if migration_integrity_issue
            else "- Migration integrity: `PASS`"
        ),
        f"- Study ID: `{status.study_id or 'NOT_CREATED'}`",
        (
            "- Independent forward research events: "
            f"`{status.formal_forward_event_count} / {required}`"
        ),
        (
            "- Remaining independent events before minimum evaluation: "
            f"`{status.remaining_independent_decision_count}`"
        ),
        (
            "- Mature final-horizon future events: "
            f"`{status.formal_mature_future_event_count}`"
        ),
        f"- Stored assignments: `{status.assignment_count}`",
        f"- Stored observation versions (latest series): `{status.observation_count}`",
    ]
    if migration_integrity_issue:
        lines.extend(
            [
                (
                    "- Migration issue: "
                    f"`{migration_integrity_issue.replace('`', '')}`"
                ),
                (
                    "- Status read mode: `READ_ONLY`; no SQLite checksum or "
                    "schema state was changed."
                ),
            ]
        )
    lines.extend(
        [
            "",
            "## Research chain",
            "",
            "`ResearchMemo → ShadowDecision → Future Observation`",
            "",
        ]
    )
    if report is None or report.research_quality is None:
        lines.extend(
            [
                "- ResearchMemo count: `0`",
                "- ShadowDecision count: `0`",
                "- Complete chain count: `0`",
                "- Thesis invalidation reasons: `{}`",
            ]
        )
    else:
        quality = report.research_quality
        lines.extend(
            [
                f"- ResearchMemo count: `{quality.research_memo_count}`",
                f"- ShadowDecision count: `{quality.shadow_decision_count}`",
                f"- Complete chain count: `{quality.complete_chain_count}`",
                (
                    "- Thesis status counts: "
                    f"`{_render_counts(quality.thesis_status_counts)}`"
                ),
                (
                    "- Thesis invalidation reasons: "
                    f"`{_render_counts(quality.invalidation_reason_counts)}`"
                ),
            ]
        )
    lines.extend(
        [
            "",
            "## Evaluation",
            "",
            "| Dimension | Status | Evidence |",
            "|---|---|---|",
        ]
    )
    lines.extend(_evaluation_rows(report))
    lines.extend(
        [
            "",
            "All three dimensions remain `COLLECTING` until at least "
            f"{required} independently registered, real forward research events "
            "and their required future observations exist.",
            "",
            "## Hard boundaries",
            "",
            "- This system evaluates persistence of research views; it does not predict returns.",
            "- Historical replay and backtests cannot satisfy the formal forward-event count.",
            "- Each ResearchMemo or ShadowDecision can count as only one independent event.",
            "- Recorded prices, volume, MFE, and MAE must reconcile to frozen 5m OHLCV bars.",
            "- Reinforcement learning is disabled.",
            "- Dynamic or online weight changes are disabled.",
            "- Automatic Skill modification is disabled.",
            "- Broker execution and automatic real trading are disabled.",
            "",
        ]
    )
    return "\n".join(lines)


def _latest_report(
    service: ShadowEvaluationService,
    study_id: str | None,
    report_id: str | None,
) -> ShadowEvaluationReport | None:
    if study_id is None or report_id is None:
        return None
    return service.repository.get_report(report_id)


def _evaluation_rows(report: ShadowEvaluationReport | None) -> list[str]:
    if report is None:
        return [
            "| Skill performance | COLLECTING | No evaluation report |",
            "| Committee performance | COLLECTING | No evaluation report |",
            "| Research quality | COLLECTING | No evaluation report |",
        ]
    skill_status = (
        ShadowPerformanceStatus.EVALUATED
        if report.skill_performance
        and all(
            item.status is ShadowPerformanceStatus.EVALUATED
            for item in report.skill_performance
        )
        else ShadowPerformanceStatus.COLLECTING
    )
    skill_pairs = sum(item.paired_event_count for item in report.skill_performance)
    committee = report.committee_performance
    quality = report.research_quality
    return [
        (
            f"| Skill performance | {skill_status.value} | "
            f"{skill_pairs} paired event(s) across {len(report.skill_performance)} Skill arm(s) |"
        ),
        (
            "| Committee performance | "
            f"{(committee.status if committee else ShadowPerformanceStatus.COLLECTING).value} | "
            f"{committee.independent_event_count if committee else 0} independent event(s) |"
        ),
        (
            "| Research quality | "
            f"{(quality.status if quality else ShadowPerformanceStatus.COLLECTING).value} | "
            f"{quality.complete_chain_count if quality else 0} complete chain(s) |"
        ),
    ]


def _render_counts(values: Mapping[Any, int]) -> str:
    return ", ".join(
        f"{getattr(key, 'value', key)}={values[key]}"
        for key in sorted(values, key=str)
    ) or "{}"


__all__ = ["render_phase7_status", "write_phase7_status"]
