"""Stable Serenity schema facade.

Legacy contract implementations remain in :mod:`astock.schemas.serenity_v2` so historical
artifacts and imports continue to validate. New deterministic adaptation schemas live in
this package and new call sites should import through this facade.
"""

from astock.schemas.serenity.compiler import (
    CanonicalDailyTrendCompileRequest,
    CanonicalFundamentalBinding,
)
from astock.schemas.serenity_v2 import (
    DailySeriesV2,
    DailyTrendDiagnosticRequestV2,
    DailyTrendHealthContractV2,
    EstimateRevisionV2,
    EventToAlphaContractV2,
    EventToAlphaDiagnosticRequestV2,
    FundamentalGrowthV2,
    GrowthHypothesisId,
    GrowthPosteriorStepV2,
    GrowthProbabilityContractV2,
    GrowthProbabilityDiagnosticRequestV2,
    GrowthProbabilityInputV2,
    GrowthValuationContractV2,
    GrowthValuationDiagnosticRequestV2,
    IndustryBottleneckContractV2,
    IndustryBottleneckDiagnosticRequestV2,
    JuglarCounterEvidenceV1,
    JuglarCycleDiagnosticRequestV2,
    JuglarCycleDimension,
    JuglarCycleStageContractV1,
    JuglarDimensionScoreV1,
    JuglarMigrationSignalV1,
    JuglarStage,
    JuglarStageProbabilityV1,
    MemoScenarioCase,
    MovingAverageV2,
    ResearchMemoComposeRequestV2,
    SerenityContractKind,
    SerenityMethodContractV2,
    SpecialistDiagnosticRequestV2,
    StructuredResearchMemoV2,
)

__all__ = [
    "CanonicalDailyTrendCompileRequest",
    "CanonicalFundamentalBinding",
    "DailySeriesV2",
    "DailyTrendDiagnosticRequestV2",
    "DailyTrendHealthContractV2",
    "EstimateRevisionV2",
    "EventToAlphaContractV2",
    "EventToAlphaDiagnosticRequestV2",
    "FundamentalGrowthV2",
    "GrowthHypothesisId",
    "GrowthPosteriorStepV2",
    "GrowthProbabilityContractV2",
    "GrowthProbabilityDiagnosticRequestV2",
    "GrowthProbabilityInputV2",
    "GrowthValuationContractV2",
    "GrowthValuationDiagnosticRequestV2",
    "IndustryBottleneckContractV2",
    "IndustryBottleneckDiagnosticRequestV2",
    "JuglarCounterEvidenceV1",
    "JuglarCycleDiagnosticRequestV2",
    "JuglarCycleDimension",
    "JuglarCycleStageContractV1",
    "JuglarDimensionScoreV1",
    "JuglarMigrationSignalV1",
    "JuglarStage",
    "JuglarStageProbabilityV1",
    "MemoScenarioCase",
    "MovingAverageV2",
    "ResearchMemoComposeRequestV2",
    "SerenityContractKind",
    "SerenityMethodContractV2",
    "SpecialistDiagnosticRequestV2",
    "StructuredResearchMemoV2",
]
