"""Account choice comes from the request, not the supplied output container.

All money and account events are generated by canonical services in isolated
project-local test databases. No production accounts or external calls.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from astock.core.object_store import ObjectStore
from astock.core.state import StateStore
from astock.investor_orchestration.capabilities import CapabilityExecutionResult
from astock.investor_orchestration.models import InvestorAnswer
from astock.investor_orchestration.service import InvestorOrchestrationService
from astock.investor_orchestration.store import InvestorOrchestrationStore
from astock.paper_trading.ledger import LedgerService
from tests.unit.test_investor_orchestration_guards import Environment, registered, request_for


@pytest.fixture
def environment(tmp_path: Path) -> Environment:
    store = InvestorOrchestrationStore(tmp_path / "state.sqlite")
    store.initialize()
    state = StateStore(store.path)
    objects = ObjectStore(tmp_path / "objects" / "sha256")
    ledger = LedgerService(state, objects)
    ledger.initialize_account("guard-paper-account", 100_000)
    return Environment(store, state, objects, ledger)


def _publish(
    environment: Environment,
    *,
    selected: str | None,
    supplied: str,
    default_hint: str | None = None,
) -> InvestorAnswer:
    request = request_for(
        account_id=selected,
        metadata={} if default_hint is None else {"default_account_id": default_hint},
    )
    nav = environment.ledger.portfolio_nav(supplied, as_of=request.question_time)
    artifact_id = registered(environment, nav)
    service = InvestorOrchestrationService(environment.store)
    _, _, coverage = service.execute(
        request,
        handlers={"PAPER": lambda *_: CapabilityExecutionResult(artifact_ids=(artifact_id,))},
    )
    return service.publish_verified(coverage_receipt_id=coverage.receipt_id)


def test_multiple_accounts_without_selection_cannot_borrow_one_supplied_nav(
    environment: Environment,
) -> None:
    environment.ledger.initialize_account("second-paper-account", 987_650)
    answer = _publish(environment, selected=None, supplied="second-paper-account")
    assert answer.degraded
    assert "9876.5" not in answer.model_dump_json()


def test_only_one_existing_account_can_be_resolved_without_guessing(
    environment: Environment,
) -> None:
    answer = _publish(environment, selected=None, supplied="guard-paper-account")
    assert not answer.degraded
    assert answer.conclusion == "该模拟账户可用现金为1000元。"


def test_explicit_selection_allows_the_right_account_among_multiple(
    environment: Environment,
) -> None:
    environment.ledger.initialize_account("second-paper-account", 987_650)
    answer = _publish(environment, selected="second-paper-account", supplied="second-paper-account")
    assert not answer.degraded
    assert answer.conclusion == "该模拟账户可用现金为9876.5元。"


def test_explicit_account_selection_cannot_be_overridden_by_supplied_nav(
    environment: Environment,
) -> None:
    environment.ledger.initialize_account("second-paper-account", 987_650)
    answer = _publish(environment, selected="guard-paper-account", supplied="second-paper-account")
    assert answer.degraded
    assert "9876.5" not in answer.model_dump_json()


def test_unverified_metadata_hint_is_not_a_configured_default_account(
    environment: Environment,
) -> None:
    environment.ledger.initialize_account("second-paper-account", 987_650)
    answer = _publish(
        environment,
        selected=None,
        supplied="second-paper-account",
        default_hint="second-paper-account",
    )
    assert answer.degraded
    assert "9876.5" not in answer.model_dump_json()
